### ISSUE TITLE
macOS build crashes after awhile or causes computer to become near unresponsive

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/lamd#4]
As reported by a user:

```
froze up internet access again...
(node:10022) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: getaddrinfo ENOTFOUND live.ksmobile.net live.ksmobile.net:80
(node:10022) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10022) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: getaddrinfo ENOTFOUND live.ksmobile.net live.ksmobile.net:80
(node:10022) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: getaddrinfo ENOTFOUND live.ksmobile.net live.ksmobile.net:80
(node:10022) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: getaddrinfo ENOTFOUND live.ksmobile.net live.ksmobile.net:80
(node:10022) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: getaddrinfo ENOTFOUND live.ksmobile.net live.ksmobile.net:80
(node:10022) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error: getaddrinfo ENOTFOUND live.ksmobile.net live.ksmobile.net:80
(node:10022) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): Error: getaddrinfo ENOTFOUND live.ksmobile.net live.ksmobile.net:80
now opening LAMD terminal gives error and won't load it...
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at fs.readFile (/snapshot/lamd/lamd.js:0:0)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

**Comment by thecoder75** [comment]
Since I don't have a macOS computer to test and verify this issue on, I am running in the dark as to the cause.

**Comment by thecoder75** [comment]
The problem was found to be a corrupt `accounts.json` file.  Fixing it removed the errors.
